[package]
name = "obxr"
version = "0.1.1"
authors = ["Maya MacLean"]

[dependencies]
clap = "2.32.0"
dialoguer = "0.1.0"
indicatif = "0.9.0"
rust_sodium = "0.9.0"
sodium_stream = { path = "../sodium_stream" }
